---

- name: Generate paste's dynamic configuration for Traefik
  template:
    src: 'paste.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}\
           /paste.toml"
    mode: '0444'

- name: Start privatebin container
  community.general.docker_container:
    cap_drop:
      - all
    container_default_behavior: 'no_defaults'
    detach: true
    env:
      TZ: 'Europe/Paris'
      PHP_TZ: 'Europe/Paris'
    hostname: '{{ services.containers.paste.name }}'
    image: '{{ services.containers.paste.image }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.volatile }}\
                 {{ services.containers.paste.volumes.data.path }}"
        target: '/srv/data'
        read_only: false
    name: '{{ services.containers.paste.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.paste.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    read_only: true
    restart_policy: unless-stopped
