---

# This is the main playbook for our infrastructure
- name: Deploy whole infrastructure
  hosts: server
  gather_facts: false
  vars_files:
    - vaulted_vars/secrets
  roles:
    - role: setup_sshd
    - role: setup_unattended_upgrades
    - role: setup_firewall
    - role: install_docker
    - role: create_directories
    - role: create_networks
    - role: start_traefik
    - role: start_files
    - role: start_paste
    - role: start_gitlab
    - role: start_wireguard
    - role: start_jupyterhub
    - role: start_matrix
