---

- name: Generate files' dynamic configuration for Traefik
  template:
    src: 'files.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}\
           /files.toml"
    mode: '0444'

- name: Start transfer.sh container
  community.general.docker_container:
    cap_drop:
      - all
    command:
      - '--provider=local'
      - '--basedir={{ services.volumes.dest.base }}'
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.files.name }}'
    image: '{{ services.containers.files.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.volatile }}\
                 {{ services.containers.files.volumes.data.path }}"
        target: '{{ services.volumes.dest.base }}'
        read_only: false
    name: '{{ services.containers.files.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.files.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
