---

- name: Generate Synapse's dynamic Traefik configuration
  template:
    src: 'synapse.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}/synapse.toml"
    mode: '0444'

- name: Generate Synapse's homeserver configuration
  template:
    src: 'homeserver.yaml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.persistent }}\
           {{ services.containers.synapse.volumes.data.path }}/homeserver.yaml"
    mode: '0444'

- name: Copy Synapse's configuration files
  copy:
    src: '{{ item.name }}'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.persistent }}\
           {{ services.containers.synapse.volumes.data.path }}\
           /{{ item.name }}"
    owner: '991'
    group: '991'
    mode: '0600'
  loop:
    - {name: '{{ setup.tld }}.log.config'}
    - {name: '{{ setup.tld }}.signing.key'}

- name: Generate Facebook registration file
  template:
    src: 'facebook_registration.yaml.j2'
    dest: '{{ item }}'
    owner: '991'
    group: '991'
    mode: '0600'
  loop:
    - "{{ services.volumes.src.base }}\
       {{ services.volumes.src.generated }}\
       {{ services.containers.synapse.volumes.facebook_registration.path }}\
           /registration.yaml"
    - "{{ services.volumes.src.base }}\
       {{ services.volumes.src.persistent }}\
       {{ services.containers.facebook_bridge.volumes.data.path }}\
           /registration.yaml"

- name: Generate Telegram registration file
  template:
    src: 'telegram_registration.yaml.j2'
    dest: '{{ item }}'
    owner: '991'
    group: '991'
    mode: '0600'
  loop:
    - "{{ services.volumes.src.base }}\
       {{ services.volumes.src.generated }}\
       {{ services.containers.synapse.volumes.telegram_registration.path }}\
           /registration.yaml"
    - "{{ services.volumes.src.base }}\
       {{ services.volumes.src.persistent }}\
       {{ services.containers.telegram_bridge.volumes.data.path }}\
           /registration.yaml"

- name: Generate WhatsApp registration file
  template:
    src: 'whatsapp_registration.yaml.j2'
    dest: '{{ item }}'
    owner: '991'
    group: '991'
    mode: '0600'
  loop:
    - "{{ services.volumes.src.base }}\
       {{ services.volumes.src.generated }}\
       {{ services.containers.synapse.volumes.whatsapp_registration.path }}\
           /registration.yaml"
    - "{{ services.volumes.src.base }}\
       {{ services.volumes.src.persistent }}\
       {{ services.containers.whatsapp_bridge.volumes.data.path }}\
           /registration.yaml"

- name: Start Synapse container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    env:
      TZ: 'Europe/Paris'
    hostname: '{{ services.containers.synapse.name }}'
    image: '{{ services.containers.synapse.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.synapse.volumes.data.path }}"
        target: '/data'
        read_only: false
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
          {{ services.containers.synapse.volumes.facebook_registration.path }}"
        target: '/registration/facebook'
        read_only: true
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
          {{ services.containers.synapse.volumes.telegram_registration.path }}"
        target: '/registration/telegram'
        read_only: true
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
          {{ services.containers.synapse.volumes.whatsapp_registration.path }}"
        target: '/registration/whatsapp'
        read_only: true
    name: '{{ services.containers.synapse.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.synapse.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped

- name: Create directory for federation files
  file:
    path: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.synapse_federation.volumes.data.path }}\
           /.well-known/matrix"
    state: 'directory'
    owner: '101'
    group: '101'
    mode: '0700'

- name: Generate federation files
  template:
    src: '{{ item }}.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.synapse_federation.volumes.data.path }}\
           /.well-known/matrix/{{ item }}"
    owner: '101'
    group: '101'
    mode: '0444'
  loop:
    - 'client'
    - 'server'

- name: Generate Synapse federation's CORS headers configuration
  template:
    src: 'cors_headers.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}\
           /cors_headers.toml"
    mode: '0444'

- name: Generate Synapse federation's dynamic Traefik configuration
  template:
    src: 'synapse-federation.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}\
           /synapse-federation.toml"
    mode: '0444'

- name: Start Synapse federation container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.synapse_federation.name }}'
    image: '{{ services.containers.synapse_federation.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
                 {{ services.containers.synapse_federation.volumes.data.path }}"
        target: '/usr/share/nginx/html'
        read_only: false
    name: '{{ services.containers.synapse_federation.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.synapse_federation.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped

- name: Generate Matrix bot's configuration
  template:
    src: 'bot_config.yaml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.persistent }}\
           {{ services.containers.matrix_bot.volumes.data.path }}\
           /config.yaml"
    owner: '1337'
    group: '1337'
    mode: '0644'

- name: Generate Matrix bot's dynamic Traefik configuration
  template:
    src: 'matrix_bot.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}/matrix_bot.toml"
    mode: '0444'

- name: Start Matrix bot container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.matrix_bot.name }}'
    image: '{{ services.containers.matrix_bot.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.matrix_bot.volumes.data.path }}"
        target: '/data'
        read_only: false
    name: '{{ services.containers.matrix_bot.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.matrix_bot.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped

- name: Generate Element's dynamic Traefik configuration
  template:
    src: 'element.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}/element.toml"
    mode: '0444'

- name: Generate Element's configuration
  template:
    src: 'element-config.json.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.element.volumes.config.path }}/config.json"
    mode: '0444'

- name: Start Element web container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.element.name }}'
    image: '{{ services.containers.element.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    name: '{{ services.containers.element.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.element.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
                 {{ services.containers.element.volumes.config.path }}\
                 /config.json"
        target: '/app/config.json'
        read_only: true

- name: Generate Facebook bridge's configuration
  template:
    src: 'facebook_config.yaml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.persistent }}\
           {{ services.containers.facebook_bridge.volumes.data.path }}\
           /config.yaml"
    owner: '1337'
    group: '1337'
    mode: '0644'

- name: Start Facebook bridge container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.facebook_bridge.name }}'
    image: '{{ services.containers.facebook_bridge.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    name: '{{ services.containers.facebook_bridge.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.facebook_bridge.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.facebook_bridge.volumes.data.path }}"
        target: '/data'
        read_only: false

- name: Generate Telegram bridge's configuration
  template:
    src: 'telegram_config.yaml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.persistent }}\
           {{ services.containers.telegram_bridge.volumes.data.path }}\
           /config.yaml"
    owner: '1337'
    group: '1337'
    mode: '0644'

- name: Start Telegram bridge container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.telegram_bridge.name }}'
    image: '{{ services.containers.telegram_bridge.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    name: '{{ services.containers.telegram_bridge.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.telegram_bridge.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.telegram_bridge.volumes.data.path }}"
        target: '/data'
        read_only: false

- name: Generate WhatsApp bridge's configuration
  template:
    src: 'whatsapp_config.yaml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.persistent }}\
           {{ services.containers.whatsapp_bridge.volumes.data.path }}\
           /config.yaml"
    owner: '1337'
    group: '1337'
    mode: '0644'

- name: Start WhatsApp bridge container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.whatsapp_bridge.name }}'
    image: '{{ services.containers.whatsapp_bridge.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    name: '{{ services.containers.whatsapp_bridge.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.whatsapp_bridge.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.whatsapp_bridge.volumes.data.path }}"
        target: '/data'
        read_only: false
