---

- name: Restart Traefik container
  community.docker.docker_container:
    name: '{{ services.containers.traefik.name }}'
    state: started
    restart: true
    container_default_behavior: 'no_defaults'
