---

- name: Restart Traefik container
  community.general.docker_container:
    name: '{{ containers.traefik.name }}'
    state: started
    restart: true
    container_default_behavior: 'no_defaults'
