---

- name: Generate JupyterHub's dynamic configuration for Traefik
  template:
    src: 'jupyterhub.toml.j2'
    dest: '{{ base_dir }}{{ generated_dir }}/traefik/dynamic/jupyterhub.toml'
    mode: '0444'

- name: Create directories for JupyterHub users
  file:
    path: '{{ base_dir }}{{ persistent_dir }}/jupyterhub/data/{{ item }}'
    state: directory
    owner: '1000'
    group: '100'
    mode: '{{ item.mode | default(volumes.default.mode, true) }}'
  loop: '{{ jupyterhub.users }}'

- name: Start JupyterHub container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    env:
      ADMIN_USER: '{{ jupyterhub.admin_user }}'
      GITLAB_URL: 'https://gitlab.{{ tld }}'
      HUB_CONNECT_IP: '{{ containers.jupyterhub.name }}'
      NETWORK_NAME: '{{ default_network }}'
      OAUTH_CALLBACK_URL: 'https://jupyterhub.{{ tld }}/hub/oauth_callback'
      OAUTH_CLIENT_ID: '{{ secrets.jupyterhub.app_id }}'
      OAUTH_CLIENT_SECRET: '{{ secrets.jupyterhub.secret }}'
      USER_HOME_DIR: '{{ base_dir }}{{ persistent_dir }}/jupyterhub/data'
    hostname: '{{ containers.jupyterhub.name }}'
    image: '{{ containers.jupyterhub.image }}'
    mounts:
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        read_only: false
    name: '{{ containers.jupyterhub.name }}'
    networks:
      - name: '{{ default_network }}'
        aliases:
          - '{{ containers.jupyterhub.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
