---

- name: Install Wireguard and QRencode
  apt:
    autoclean: true
    autoremove: true
    state: latest
    pkg:
      - wireguard
      - qrencode

- name: Generate server config
  template:
    src: 'server.conf.j2'
    dest: '{{ base_dir }}{{ persistent_dir }}/wireguard/data/wg-sadm.conf'
    mode: '0400'

- name: Generate client configs
  template:
    src: 'client.conf.j2'
    dest: >-
      '{{ base_dir }}{{ persistent_dir }}/wireguard/data/{{ item.name }}.conf'
    mode: '0400'
  loop: '{{ secrets.wireguard_peers }}'
  loop_control:
    label: '{{ item.name }}'

- name: Generate Wireguard's dynamic configuration for Traefik
  template:
    src: 'wireguard.toml.j2'
    dest: '{{ base_dir }}{{ generated_dir }}/traefik/dynamic/wireguard.toml'
    mode: '0444'

- name: Start Wireguard container
  community.general.docker_container:
    capabilities:
      - net_admin
      - sys_module
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ containers.wireguard.name }}'
    image: '{{ containers.wireguard.image }}'
    mounts:
      - type: bind
        source: '{{ base_dir }}{{ persistent_dir }}/wireguard/data'
        target: '{{ volumes.prefix }}'
        read_only: true
      - type: bind
        source: '/lib/modules'
        target: '/lib/modules'
        read_only: true
    name: '{{ containers.wireguard.name }}'
    networks:
      - name: '{{ default_network }}'
        aliases:
          - '{{ containers.wireguard.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
