---

- name: Generate gitlab's dynamic configuration for Traefik
  template:
    src: 'gitlab.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}\
           /gitlab.toml"
    mode: '0444'

- name: Start GitLab server container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.{{ setup.tld }}'
        gitlab_rails['time_zone'] = 'Europe/Paris'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        letsencrypt['enable'] = false
        prometheus_monitoring['enable'] = false

        registry_external_url 'https://registry.{{ setup.tld }}'
        registry_nginx['listen_port'] = 5100
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        pages_external_url 'https://pages.{{ setup.tld }}'
        pages_nginx['listen_port'] = 5200
        pages_nginx['listen_https'] = false
        pages_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        gitlab_pages['inplace_chroot'] = true
    hostname: '{{ services.containers.gitlab.name }}'
    image: '{{ services.containers.gitlab.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.gitlab.volumes.config.path }}"
        target: '/etc/gitlab'
        read_only: false
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.gitlab.volumes.log.path }}"
        target: '/var/log/gitlab'
        read_only: false
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.gitlab.volumes.data.path }}"
        target: '/var/opt/gitlab'
        read_only: false
    name: '{{ services.containers.gitlab.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.gitlab.name }}'
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    restart_policy: unless-stopped

- name: Start GitLab runner container
  community.general.docker_container:
    container_default_behavior: 'no_defaults'
    detach: true
    env:
      TZ: 'Europe/Paris'
    hostname: '{{ services.containers.gitlab_runner.name }}'
    image: '{{ services.containers.gitlab_runner.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.gitlab_runner.volumes.config.path }}"
        target: '/etc/gitlab-runner'
        read_only: false
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        read_only: false
    name: '{{ services.containers.gitlab_runner.name }}'
    networks:
      - name: "bridge"
    networks_cli_compatible: false
    pull: true
    purge_networks: true
    privileged: true
    restart_policy: unless-stopped
