---

- name: Generate Traefik's static configuration
  template:
    src: 'static.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.static.path }}/traefik.toml"
    mode: '0444'
  notify: Restart Traefik container

- name: Generate Traefik's dynamic configuration
  template:
    src: 'dynamic.toml.j2'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}/traefik.toml"
    mode: '0444'

- name: Copy Traefik's generic dynamic configuration files
  copy:
    src: '{{ item.name }}'
    dest: "{{ services.volumes.src.base }}\
           {{ services.volumes.src.generated }}\
           {{ services.containers.traefik.volumes.dynamic.path }}\
           /{{ item.name }}"
    mode: '0444'
  loop:
    - {name: 'security-headers.toml'}
    - {name: 'tls.toml'}

- name: Start Traefik container
  community.general.docker_container:
    cap_drop:
      - all
    capabilities:
      - net_bind_service
    command:
      - "--configFile={{ services.volumes.dest.base }}\
                      {{ services.containers.traefik.volumes.static.path }}\
                      /traefik.toml"
    container_default_behavior: 'no_defaults'
    detach: true
    hostname: '{{ services.containers.traefik.name }}'
    image: '{{ services.containers.traefik.image }}'
    log_driver: '{{ services.log.driver }}'
    log_options: '{{ services.log.options }}'
    mounts:
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
                 {{ services.containers.traefik.volumes.static.path }}"
        target: "{{ services.volumes.dest.base }}\
                 {{ services.containers.traefik.volumes.static.path }}"
        read_only: true
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.generated }}\
                 {{ services.containers.traefik.volumes.dynamic.path }}"
        target: "{{ services.volumes.dest.base }}\
                 {{ services.containers.traefik.volumes.dynamic.path }}"
        read_only: true
      - type: bind
        source: "{{ services.volumes.src.base }}\
                 {{ services.volumes.src.persistent }}\
                 {{ services.containers.traefik.volumes.data.path }}"
        target: "{{ services.volumes.dest.base }}\
                 {{ services.containers.traefik.volumes.data.path }}"
        read_only: false
    name: '{{ services.containers.traefik.name }}'
    networks:
      - name: '{{ services.network }}'
        aliases:
          - '{{ services.containers.traefik.name }}'
    networks_cli_compatible: false
    published_ports:
      - '22:22/tcp'
      - '80:80/tcp'
      - '443:443/tcp'
      - '51820:51820/udp'
    pull: true
    purge_networks: true
    restart_policy: unless-stopped
